### ISSUE TITLE
Kyoto.js 12

### ISSUE THREAD

**Issue by fand** [kyotojs/meetup#3]
https://kyotojs.connpass.com/event/46417/

# 場所
NOTA Inc.

# 日時
- 2017-01-21 (土)

**Comment by fand** [comment]
# TODO

## 事前準備

- [x] 〜1ヶ月前 会社・会場の承認を得る
- [x] 2週間前 発表者集め
  - 告知前にある程度集めておくと良い
- [x] 2週間前 告知
  - 技術イベントの場合、2週間前に告知、くらいが適当
  - 早すぎても話題がなくなっちゃうし、遅すぎると人が集まらない  
- [x] 2週間前 スタッフ集め
  - 発表者
  - 設営
  - 受付
  - 入り口の案内
  - カメラマン
  - Slackに専用チャンネル作ると楽そう
- [x] 1週間前 天気チェック
- [ ] 1週間前 おもてなし
  - ようこそスライド作成 (WiFi, トイレ, 立ち入り禁止エリア)
  - 会場BGM用意
  - 発表のBGM
- [ ] 1日前 設営準備、機材チェック
  - プロジェクタ、ディスプレイ
  - マイク、音楽
  - タイマー
- [x] 1日前 会場準備（できれば）

## 当日準備

- [ ] ビル入り口にイベント会場への案内（できれば）
- [x] 案内の人をおく（できれば）
- [ ] 入口や壁に会場の案内を書く
  - 無線LAN
  - トイレ
  - ハッシュタグ
- [ ] スタッフは名札を下げる（できれば）
  - 「名札のある人がスタッフです」とか言っておくと話しかけやすい
- [x] 参加人数にもよるが、マイクなど音響準備
- [x] Ustreamするなら、Ustream準備
- [ ] 出席者アンケート
- [x] 雨の場合は傘立てを用意

## 懇親会

- [ ] 参加費回収
- [ ] 飲食注文
  - 適量
    - 寿司 TBD
    - ピザ TBD
    - ビール TBD

## 事後
- [ ] 発表資料まとめる
  - connpassとか
- [ ] 参加者多い場合はtogetterとかあると吉？
- [ ] まとめブログ書く
- [ ] KPT

**Comment by fand** [comment]
# 精算
| 項目 |金額|
|:-------:|:------:|
| 参加費 | +8000 |
| 飲み物、おかし | -3819 |
| ピザ | -2697 |
| ゴミ袋 | -560 |

残額924円
