### ISSUE TITLE
Kyoto.js 13

### ISSUE THREAD

**Issue by fand** [kyotojs/meetup#5]
https://kyotojs.connpass.com/event/60422/

# TODO

## 事前準備

- [x] 〜1ヶ月前 会社・会場の承認を得る
- [x] 2週間前 発表者集め
  - 告知前にある程度集めておくと良い
- [x] 2週間前 告知
  - 技術イベントの場合、2週間前に告知、くらいが適当
  - 早すぎても話題がなくなっちゃうし、遅すぎると人が集まらない  
- [ ] 2週間前 スタッフ集め
  - 発表者
  - 設営
  - 受付
  - 入り口の案内
  - カメラマン
  - Slackに専用チャンネル作ると楽そう
- [x] 1日前 天気チェック
- [x] 1日前 おもてなし
  - ようこそスライド作成 (WiFi, トイレ, 立ち入り禁止エリア)
  - 会場BGM用意
  - 発表のBGM
  - 名札用のヒモを用意
- [x] 1日前 設営準備、機材チェック
  - プロジェクタ、ディスプレイ
  - マイク、音楽
  - タイマー
- [x] 1日前 会場準備（できれば）

## 当日準備

- [ ] ビル入り口にイベント会場への案内（できれば）
- [x] 案内の人をおく（できれば）
- [x] 入口や壁に会場の案内を書く
  - 無線LAN
  - トイレ
  - ハッシュタグ
- [x] 名札を印刷
- [x] スタッフは名札を下げる（できれば）
  - 「名札のある人がスタッフです」とか言っておくと話しかけやすい
- [ ] 参加人数にもよるが、マイクなど音響準備
- [ ] Ustreamするなら、Ustream準備
- [ ] 出席者アンケート
- [ ] 雨の場合は傘立てを用意

## 懇親会

- [x] 参加費回収
- [x] 飲食注文
  - 適量
    - 寿司 TBD
    - ピザ TBD
    - ビール TBD

## 事後
- [ ] 発表資料まとめる
  - connpassとか
- [ ] 参加者多い場合はtogetterとかあると吉？
- [ ] まとめブログ書く
- [ ] KPT

**Comment by fand** [comment]
# 精算

- 支出: 22480
  - 前回の余剰金: 924
  - 参加費*21: 21000
- 支出: 15064
  - 名札: 1480
  - お酒第一弾: 3597
  - お酒第二弾: 3405
  - ピザ: 6582
- 余剰金: 6860
